export const  popularStocks= [
{ label: "Apple Inc.", value: "AAPL" },
{ label: "Microsoft Corporation", value: "MSFT" },
{ label: "Amazon.com Inc.", value: "AMZN" },
{ label: "Alphabet Inc. (Google) Class A", value: "GOOGL" },
{ label: "Alphabet Inc. (Google) Class C", value: "GOOG" },
{ label: "Meta Platforms Inc. (formerly Facebook)", value: "FB" },
{ label: "Berkshire Hathaway Inc. Class A", value: "BRK.A" },
{ label: "Berkshire Hathaway Inc. Class B", value: "BRK.B" },
{ label: "Visa Inc.", value: "V" },
{ label: "Johnson & Johnson", value: "JNJ" },
{ label: "Walmart Inc.", value: "WMT" },
{ label: "Procter & Gamble Company", value: "PG" },
{ label: "Tesla Inc.", value: "TSLA" },
{ label: "NVIDIA Corporation", value: "NVDA" },
{ label: "JPMorgan Chase & Co.", value: "JPM" },
{ label: "Mastercard Incorporated", value: "MA" },
{ label: "UnitedHealth Group Incorporated", value: "UNH" },
{ label: "Home Depot Inc.", value: "HD" },
{ label: "Walt Disney Company", value: "DIS" },
{ label: "Alibaba Group Holding Limited", value: "BABA" },
{ label: "Verizon Communications Inc.", value: "VZ" },
{ label: "Coca-Cola Company", value: "KO" },
{ label: "Pfizer Inc.", value: "PFE" },
{ label: "Netflix Inc.", value: "NFLX" },
{ label: "AT&T Inc.", value: "T" },
{ label: "Bank of America Corp", value: "BAC" },
{ label: "Intel Corporation", value: "INTC" },
{ label: "Cisco Systems, Inc.", value: "CSCO" },
{ label: "Oracle Corporation", value: "ORCL" },
{ label: "Qualcomm Inc", value: "QCOM" },
{ label: "Boeing Co", value: "BA" },
{ label: "Goldman Sachs Group Inc", value: "GS" },
{ label: "Morgan Stanley", value: "MS" },
{ label: "American Express Company", value: "AXP" },
{ label: "International Business Machines Corporation", value: "IBM" },
{ label: "3M Company", value: "MMM" },
{ label: "Honeywell International Inc.", value: "HON" },
{ label: "McDonald's Corporation", value: "MCD" },
{ label: "The Coca-Cola Company", value: "KO" },
{ label: "PepsiCo, Inc.", value: "PEP" },
]